---
# tasks file for zabbix-install
- name: Configure postgresql to preferred major version
  ansible.builtin.dnf:
    update_cache: true    
    name: "@postgresql:{{ zabbix_postgresql_version }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

- name: Configure php to preferred major version
  ansible.builtin.dnf:
    update_cache: true    
    name: "@php:{{ zabbix_php_version }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

- name: Install official zabbix repository
  ansible.builtin.dnf:
    # GPG check disabled intentionally as the official documentation does not provide GPG verification in install guide
    # Eventually I'd like to add support manually via their repo if possible
    disable_gpg_check: true
    name: "{{ zabbix_repository_url }}"
    state: present

- name: Install necessary software
  ansible.builtin.dnf:
    update_cache: true    
    name: "{{ zabbix_required_packages }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

- name: Configure postgresql instance for hosting local database
  when:
    - zabbix_install_pgsql_init == true
  block:
    - name: Initialize the postgresql cluster
      ignore_errors: true
      register: _postgres_initdb
      ansible.builtin.command: /usr/bin/postgresql-setup --initdb

      # Protection against overwriting legitimate data
    - name: Detect install is clean-state
      when: _postgres_initdb.rc == 0 
      ansible.builtin.set_fact:
        _allow_restore_db_schema: true

    - name: Start the postgresql server
      ansible.builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true

    - name: Add zabbix user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ zabbix_database_username }}"
        password: "{{ zabbix_database_password }}"

    - name: Add zabbix database
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ zabbix_database_name }}"
        owner: "{{ zabbix_database_username }}"

    - name: Update pg_hba.conf for zabbix access
      notify:
        - Restart postgresql
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/data/pg_hba.conf
        contype: host
        users: "{{ zabbix_database_username }}"
        source: samehost
        databases: "{{ zabbix_database_name }}"
        method: md5
        create: true
    
    - name: Restart postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: Restore zabbix data set to db
      when:
        - _allow_restore_db_schema is true
      community.postgresql.postgresql_db:
        login_user: "{{ zabbix_database_username }}"
        login_password: "{{ zabbix_database_password }}"
        login_host: "{{ zabbix_database_host }}"
        name: "{{ zabbix_database_name }}"
        state: restore
        target: "/usr/share/zabbix-sql-scripts/postgresql/server.sql.gz"

#- name: configure zabbix Install
#
#- name: start zabbix server
- name: Configure and start Zabbix server
  block:
    - name: Update zabbix server configuration
      notify: Restart zabbix-server
      ansible.builtin.lineinfile:
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
        path: /etc/zabbix/zabbix_server.conf
      with_items:
        - regex: "^DBName=zabbix"
          line: "DBName={{ zabbix_database_name }}"
        - regex: "^DBUser=zabbix"
          line: "DBUser={{ zabbix_database_username}}"
        - regex: "# DBPassword="
          line: "DBPassword={{ zabbix_database_password }}"

    # Multiple changes can be staged in one lineinfile stanza, we use this here to adjust two lines in the nginx config
    - name: Configure zabbix-server nginx configuration
      ansible.builtin.lineinfile:
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
        path: /etc/nginx/conf.d/zabbix.conf
      with_items: 
        # Enable server on port 8080
        - regex: "^#        listen"
          line: "\tlisten 8080;"
        # Set server hostname
        - regex: "^#        server_name"
          line: "\tserver_name {{ zabbix_server_name }};"

    - name: Start and enable server service
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-server.service
        - zabbix-agent.service
        - nginx.service
    
    - name: Configure firewall for runtime
      ansible.builtin.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        #- https

    - name: Configure firewall for runtime
      ansible.builtin.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - "8080/tcp"
        - "10051/tcp"
        - "443/tcp"
