---
- name: Install zabbix server on target
  ansible.builtin.include_tasks: zabbix_server.yml
  when:
    - zabbix_install_proxy is false

- name: Install zabbix proxy on target
  ansible.builtin.include_tasks: zabbix_proxy.yml
  when:
    - zabbix_install_proxy is true