---
# tasks file for zabbix-install
- name: Configure postgresql to preferred major version
  ansible.builtin.dnf:
    update_cache: true    
    name: '@postgresql:15'
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"


- name: Configure php to preferred major version
  ansible.builtin.dnf:
    update_cache: true    
    name: '@php:8.1'
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

- name: Enable powertools
  community.general.ini_file:
    path: "/etc/yum.repos.d/{{ powertools_repo_file }}"
    section: "{{ powertools_repo_name }}"
    option: enabled
    value: "1"
    mode: "0644"
  notify:
    - Yum update cache
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

- name: Install official zabbix repository
  ansible.builtin.dnf:
    name: "https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm"
    state: present

- name: Install necessary software
  ansible.builtin.dnf:
    update_cache: true    
    name: "{{ zabbix_install_pkgs }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "EL", "Rocky", "AlmaLinux" ]
    - ansible_distribution_major_version >= "8"

#- name: Configure postgresql instance for hosting local database
#  block:
#    - name: Initialize the postgresql cluster
#    - name: Add zabbix user
#    - name: Add zabbix database
#    - name: Update postgresql database configuration files
#    - name: start postgresql service
#
#- name: configure zabbix Install
#
#- name: start zabbix server
#
#- name: configure firewall