---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: zabbix
    box: generic/rocky8
    memory: 2048
    cpus: 2
    interfaces:
      - network_name: forwarded_port
        guest: 8080
        host: 8080
provisioner:
  name: ansible
verifier:
  name: ansible
