---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include zabbix"
      ansible.builtin.include_role:
        name: "ansible-role-zabbix"
      vars:
        - zabbix_install_proxy: true
